### PR TITLE
Update gem dependencies for dnssd and CFPropertyList

### PR DESCRIPTION
**Pull request by sodabrew**
Gets browsing working again on OS X Yosemite.

### CODE REVIEW

**Comment by elcuervo** [comment]
Awesome. Thanks!

**Comment by sodabrew** [comment]
Unfortunately dnssd > 3.0 drops Ruby 1.9.3 support. Are you OK with that?

Also interesting is that I had to collect the nodes first before calling DNSSD.resolve on them. I was getting inconsistent results until I made `DNSSD.resolve(node)` a separate loop, then I started to see every node consistently.

I haven't looked into the unit test failures yet, but can look in the next few days.

**Comment by elcuervo** [comment]
@sodabrew I'm doing the same. I'm ok with dropping `1.9.3` support in this new version.
I'll take a look to the errors. Thank you for the PR ^_^

**Comment by sodabrew** [comment]
Awesome, thank you too!

**Pull request merged**
